import type { HomeItem } from "./types"

export const initialHomeItems: Omit<HomeItem, "id" | "created_at" | "updated_at">[] = [
  // Kitchen
  {
    item_name: "Refrigerator",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 1200,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Stove/Oven",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 800,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Microwave",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 150,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Dishwasher",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 600,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Cookware Set",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 200,
    actual_cost: null,
    quantity: 1,
    notes: "Pots and pans",
  },
  {
    item_name: "Dinnerware Set",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 100,
    actual_cost: null,
    quantity: 1,
    notes: "Plates, bowls, cups",
  },
  {
    item_name: "Cutlery Set",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 80,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Kitchen Knives",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 120,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Cutting Boards",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 40,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },
  {
    item_name: "Mixing Bowls",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 50,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Baking Sheets",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 30,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },
  {
    item_name: "Coffee Maker",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 100,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Toaster",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 40,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Blender",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 80,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Kitchen Towels",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 25,
    actual_cost: null,
    quantity: 6,
    notes: "",
  },
  {
    item_name: "Trash Can",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 50,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },

  // Living Room
  {
    item_name: "Sofa",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 1500,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Coffee Table",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 300,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "TV Stand",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 250,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Television",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 800,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Bookshelf",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 200,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Area Rug",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 300,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Curtains",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 150,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },
  {
    item_name: "Table Lamps",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 120,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },
  {
    item_name: "Throw Pillows",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 80,
    actual_cost: null,
    quantity: 4,
    notes: "",
  },
  {
    item_name: "Wall Art",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 200,
    actual_cost: null,
    quantity: 3,
    notes: "",
  },

  // Bedroom
  {
    item_name: "Bed Frame",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 600,
    actual_cost: null,
    quantity: 1,
    notes: "Queen size",
  },
  {
    item_name: "Mattress",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 1000,
    actual_cost: null,
    quantity: 1,
    notes: "Queen size",
  },
  {
    item_name: "Bed Sheets",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 80,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },
  {
    item_name: "Pillows",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 100,
    actual_cost: null,
    quantity: 4,
    notes: "",
  },
  {
    item_name: "Comforter/Duvet",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 150,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Dresser",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 500,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Nightstands",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 200,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },
  {
    item_name: "Bedside Lamps",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 100,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },
  {
    item_name: "Closet Organizers",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 150,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Hangers",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 30,
    actual_cost: null,
    quantity: 50,
    notes: "",
  },
  {
    item_name: "Alarm Clock",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 25,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Bedroom Curtains",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 120,
    actual_cost: null,
    quantity: 2,
    notes: "Blackout",
  },

  // Bathroom
  {
    item_name: "Shower Curtain",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 30,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Bath Towels",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 80,
    actual_cost: null,
    quantity: 6,
    notes: "",
  },
  {
    item_name: "Hand Towels",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 40,
    actual_cost: null,
    quantity: 6,
    notes: "",
  },
  {
    item_name: "Bath Mat",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 25,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },
  {
    item_name: "Toilet Brush",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 15,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Trash Can",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 20,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Bathroom Storage",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 100,
    actual_cost: null,
    quantity: 1,
    notes: "Shelves or cabinet",
  },
  {
    item_name: "Mirror",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 80,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Soap Dispenser",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 20,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },
  {
    item_name: "Toothbrush Holder",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 15,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },

  // Laundry
  {
    item_name: "Washing Machine",
    room_category: "Laundry",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 700,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Dryer",
    room_category: "Laundry",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 600,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Laundry Basket",
    room_category: "Laundry",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 30,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },
  {
    item_name: "Iron",
    room_category: "Laundry",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 50,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Ironing Board",
    room_category: "Laundry",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 40,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Drying Rack",
    room_category: "Laundry",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 35,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },

  // Dining Room
  {
    item_name: "Dining Table",
    room_category: "Dining Room",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 800,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Dining Chairs",
    room_category: "Dining Room",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 400,
    actual_cost: null,
    quantity: 6,
    notes: "",
  },
  {
    item_name: "Tablecloth",
    room_category: "Dining Room",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 40,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Placemats",
    room_category: "Dining Room",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 30,
    actual_cost: null,
    quantity: 6,
    notes: "",
  },
  {
    item_name: "Serving Dishes",
    room_category: "Dining Room",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 80,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },

  // Home Office
  {
    item_name: "Desk",
    room_category: "Home Office",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 400,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Office Chair",
    room_category: "Home Office",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 300,
    actual_cost: null,
    quantity: 1,
    notes: "Ergonomic",
  },
  {
    item_name: "Desk Lamp",
    room_category: "Home Office",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 60,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Filing Cabinet",
    room_category: "Home Office",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 150,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Desk Organizer",
    room_category: "Home Office",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 30,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },

  // General
  {
    item_name: "Vacuum Cleaner",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 250,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Mop and Bucket",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 40,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Broom and Dustpan",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 25,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Cleaning Supplies",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 60,
    actual_cost: null,
    quantity: 1,
    notes: "All-purpose cleaner, etc.",
  },
  {
    item_name: "Tool Kit",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 100,
    actual_cost: null,
    quantity: 1,
    notes: "Basic tools",
  },
  {
    item_name: "Step Ladder",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 60,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Fire Extinguisher",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 40,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },
  {
    item_name: "First Aid Kit",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 30,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Smoke Detectors",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 80,
    actual_cost: null,
    quantity: 4,
    notes: "",
  },
]
