import type { HomeItem } from "./types"

export const initialHomeItems: Omit<HomeItem, "id" | "created_at" | "updated_at" | "user_id">[] = [
  // Kitchen (Cozinha)
  {
    item_name: "Conjunto de panelas",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 300.0,
    actual_cost: null,
    quantity: 1,
    notes: "Obrigatório",
  },
  {
    item_name: "Frigideiras (diferentes tamanhos)",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 120.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Tábua de corte",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 40.0,
    actual_cost: null,
    quantity: 2,
    notes: "Plástico e madeira",
  },
  {
    item_name: "Jogo de facas",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 120.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Conjunto de talheres",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 150.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Pratos (rasos e fundos)",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 200.0,
    actual_cost: null,
    quantity: 1,
    notes: "Jogo de 8",
  },
  {
    item_name: "Copos para água/suco",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 100.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Xícaras para café/chá",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 80.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Potes para armazenamento",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 60.0,
    actual_cost: null,
    quantity: 1,
    notes: "Vários tamanhos",
  },
  {
    item_name: "Escorredor de louça",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 70.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Escorredor de macarrão",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 30.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Lixeira",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 50.0,
    actual_cost: null,
    quantity: 1,
    notes: "Com tampa",
  },
  {
    item_name: "Abridor de latas/garrafas",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 25.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Ralador",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 25.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Pano de prato",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 25.0,
    actual_cost: null,
    quantity: 6,
    notes: "",
  },
  {
    item_name: "Microondas",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 400.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Liquidificador",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 120.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Cafeteira",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 150.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Fogão/Forno",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 1800.0,
    actual_cost: null,
    quantity: 1,
    notes: "Gás ou elétrico",
  },
  {
    item_name: "Geladeira",
    room_category: "Kitchen",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 2500.0,
    actual_cost: null,
    quantity: 1,
    notes: "Eficiente em energia",
  },

  // Living Room (Sala de Estar)
  {
    item_name: "Sofá",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 1500.0,
    actual_cost: null,
    quantity: 1,
    notes: "3 lugares",
  },
  {
    item_name: "Rack para TV",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 250.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "TV",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 800.0,
    actual_cost: null,
    quantity: 1,
    notes: "Smart TV",
  },
  {
    item_name: "Cortinas",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 200.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Luminárias",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 100.0,
    actual_cost: null,
    quantity: 1,
    notes: "Luminária de chão ou mesa",
  },
  {
    item_name: "Mesa de centro/lateral",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 300.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Tapete",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 300.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Almofadas",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 80.0,
    actual_cost: null,
    quantity: 4,
    notes: "",
  },
  {
    item_name: "Manta para sofá",
    room_category: "Living Room",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 50.0,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },

  // Dining Room (Sala de Jantar)
  {
    item_name: "Mesa de jantar",
    room_category: "Dining Room",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 800.0,
    actual_cost: null,
    quantity: 1,
    notes: "Para 6-8 pessoas",
  },
  {
    item_name: "Cadeiras",
    room_category: "Dining Room",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 600.0,
    actual_cost: null,
    quantity: 6,
    notes: "",
  },
  {
    item_name: "Toalha de mesa",
    room_category: "Dining Room",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 40.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Jogo americano",
    room_category: "Dining Room",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 30.0,
    actual_cost: null,
    quantity: 6,
    notes: "",
  },
  {
    item_name: "Travessas para servir",
    room_category: "Dining Room",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 80.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Luminária pendente (Lustre)",
    room_category: "Dining Room",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 200.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },

  // Bedroom (Quarto)
  {
    item_name: "Cama",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 600.0,
    actual_cost: null,
    quantity: 1,
    notes: "Queen ou King size",
  },
  {
    item_name: "Colchão",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 1000.0,
    actual_cost: null,
    quantity: 1,
    notes: "Espuma ou molas",
  },
  {
    item_name: "Travesseiros",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 100.0,
    actual_cost: null,
    quantity: 4,
    notes: "",
  },
  {
    item_name: "Jogo de lençóis (pelo menos 2)",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 150.0,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },
  {
    item_name: "Edredom/cobertor",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 150.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Guarda-roupa",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 700.0,
    actual_cost: null,
    quantity: 1,
    notes: "Se não houver embutido",
  },
  {
    item_name: "Cabideiros",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 30.0,
    actual_cost: null,
    quantity: 30,
    notes: "",
  },
  {
    item_name: "Espelho (corpo inteiro)",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 80.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Cortinas",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 150.0,
    actual_cost: null,
    quantity: 1,
    notes: "Recomendado blackout",
  },
  {
    item_name: "Criado-mudo",
    room_category: "Bedroom",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 200.0,
    actual_cost: null,
    quantity: 2,
    notes: "",
  },

  // Bathroom (Banheiro)
  {
    item_name: "Jogo de toalhas (banho, rosto e mão)",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 100.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Tapete de Banho",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 25.0,
    actual_cost: null,
    quantity: 1,
    notes: "Antiderrapante",
  },
  {
    item_name: "Cortina para box",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 30.0,
    actual_cost: null,
    quantity: 1,
    notes: "Com forro",
  },
  {
    item_name: "Lixeira",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 20.0,
    actual_cost: null,
    quantity: 1,
    notes: "Pequena",
  },
  {
    item_name: "Porta-escova de dentes",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 15.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Saboneteira",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 20.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Escova sanitária",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 15.0,
    actual_cost: null,
    quantity: 1,
    notes: "Com suporte",
  },
  {
    item_name: "Espelho de Banheiro",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 60.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Armário de Remédios",
    room_category: "Bathroom",
    purchase_status: "Not Purchased",
    priority: "Medium",
    estimated_cost: 80.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },

  // Laundry (Lavanderia)
  {
    item_name: "Máquina de lavar",
    room_category: "Laundry",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 1500.0,
    actual_cost: null,
    quantity: 1,
    notes: "Front ou top load",
  },
  {
    item_name: "Varal (de chão)",
    room_category: "Laundry",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 40.0,
    actual_cost: null,
    quantity: 1,
    notes: "Dobrável",
  },
  {
    item_name: "Ferro de passar",
    room_category: "Laundry",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 60.0,
    actual_cost: null,
    quantity: 1,
    notes: "A vapor",
  },
  {
    item_name: "Tábua de passar",
    room_category: "Laundry",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 50.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Cesto para roupas (sujas)",
    room_category: "Laundry",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 30.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },

  // Home Office (Escritório)
  {
    item_name: "Mesa de Escritório",
    room_category: "Home Office",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 400.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Cadeira ergonômica",
    room_category: "Home Office",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 300.0,
    actual_cost: null,
    quantity: 1,
    notes: "Ergonômica",
  },
  {
    item_name: "Organizador de mesa",
    room_category: "Home Office",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 30.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Luminárias de Mesa",
    room_category: "Home Office",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 50.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Papelaria básica",
    room_category: "Home Office",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 20.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Filtro de linha/extensão",
    room_category: "Home Office",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 40.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Roteador Wi-Fi",
    room_category: "Home Office",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 150.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },

  // General (Geral)
  {
    item_name: "Vassoura e Pá de Lixo",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 25.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Rodo",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 15.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Balde",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 20.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Esfregão (Mop)",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 40.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Flanelas",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 15.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Luvas de Limpeza",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 10.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Produtos de Limpeza (multiuso, desinfetante, limpa-vidros)",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 80.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Kit de ferramentas básicas",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 100.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Extintor de incêndio",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 50.0,
    actual_cost: null,
    quantity: 1,
    notes: "Segurança essencial",
  },
  {
    item_name: "Kit de primeiros socorros",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 40.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Lanterna",
    room_category: "General",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 20.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },

  // Outdoor (Área Externa)
  {
    item_name: "Tapete para entrada",
    room_category: "Outdoor",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 40.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Iluminação externa",
    room_category: "Outdoor",
    purchase_status: "Not Purchased",
    priority: "High",
    estimated_cost: 100.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
  {
    item_name: "Vaso de plantas",
    room_category: "Outdoor",
    purchase_status: "Not Purchased",
    priority: "Low",
    estimated_cost: 50.0,
    actual_cost: null,
    quantity: 1,
    notes: "",
  },
]
